/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package org.github.kafka.examples.producer.serializer.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class CustomerAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerAvro\",\"namespace\":\"org.github.kafka.examples.producer.serializer.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"}]}");
    private static final long serialVersionUID = 5637948792125916475L;
    private static final SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<CustomerAvro> ENCODER =
            new BinaryMessageEncoder<CustomerAvro>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<CustomerAvro> DECODER =
            new BinaryMessageDecoder<CustomerAvro>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<CustomerAvro>
            WRITER$ = (org.apache.avro.io.DatumWriter<CustomerAvro>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<CustomerAvro>
            READER$ = (org.apache.avro.io.DatumReader<CustomerAvro>) MODEL$.createDatumReader(SCHEMA$);
    private int id;
    private java.lang.CharSequence name;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public CustomerAvro() {
    }

    /**
     * All-args constructor.
     * @param id The new value for id
     * @param name The new value for name
     */
    public CustomerAvro(java.lang.Integer id, java.lang.CharSequence name) {
        this.id = id;
        this.name = name;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<CustomerAvro> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<CustomerAvro> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<CustomerAvro> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<CustomerAvro>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Deserializes a CustomerAvro from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a CustomerAvro instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static CustomerAvro fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new CustomerAvro RecordBuilder.
     * @return A new CustomerAvro RecordBuilder
     */
    public static org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder newBuilder() {
        return new org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder();
    }

    /**
     * Creates a new CustomerAvro RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new CustomerAvro RecordBuilder
     */
    public static org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder newBuilder(org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder other) {
        if (other == null) {
            return new org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder();
        } else {
            return new org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder(other);
        }
    }

    /**
     * Creates a new CustomerAvro RecordBuilder by copying an existing CustomerAvro instance.
     * @param other The existing instance to copy.
     * @return A new CustomerAvro RecordBuilder
     */
    public static org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder newBuilder(org.github.kafka.examples.producer.serializer.avro.CustomerAvro other) {
        if (other == null) {
            return new org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder();
        } else {
            return new org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder(other);
        }
    }

    /**
     * Serializes this CustomerAvro to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return id;
            case 1:
                return name;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                id = (java.lang.Integer) value$;
                break;
            case 1:
                name = (java.lang.CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'id' field.
     * @return The value of the 'id' field.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the 'id' field.
     * @param value the value to set.
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the 'name' field.
     * @return The value of the 'name' field.
     */
    public java.lang.CharSequence getName() {
        return name;
    }

    /**
     * Sets the value of the 'name' field.
     * @param value the value to set.
     */
    public void setName(java.lang.CharSequence value) {
        this.name = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeInt(this.id);

        out.writeString(this.name);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.id = in.readInt();

            this.name = in.readString(this.name instanceof Utf8 ? (Utf8) this.name : null);

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.id = in.readInt();
                        break;

                    case 1:
                        this.name = in.readString(this.name instanceof Utf8 ? (Utf8) this.name : null);
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }

    /**
     * RecordBuilder for CustomerAvro instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerAvro>
            implements org.apache.avro.data.RecordBuilder<CustomerAvro> {

        private int id;
        private java.lang.CharSequence name;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.name)) {
                this.name = data().deepCopy(fields()[1].schema(), other.name);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing CustomerAvro instance
         * @param other The existing instance to copy.
         */
        private Builder(org.github.kafka.examples.producer.serializer.avro.CustomerAvro other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.name)) {
                this.name = data().deepCopy(fields()[1].schema(), other.name);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'id' field.
         * @return The value.
         */
        public int getId() {
            return id;
        }


        /**
         * Sets the value of the 'id' field.
         * @param value The value of 'id'.
         * @return This builder.
         */
        public org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder setId(int value) {
            validate(fields()[0], value);
            this.id = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'id' field has been set.
         * @return True if the 'id' field has been set, false otherwise.
         */
        public boolean hasId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'id' field.
         * @return This builder.
         */
        public org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder clearId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'name' field.
         * @return The value.
         */
        public java.lang.CharSequence getName() {
            return name;
        }


        /**
         * Sets the value of the 'name' field.
         * @param value The value of 'name'.
         * @return This builder.
         */
        public org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder setName(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.name = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'name' field has been set.
         * @return True if the 'name' field has been set, false otherwise.
         */
        public boolean hasName() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'name' field.
         * @return This builder.
         */
        public org.github.kafka.examples.producer.serializer.avro.CustomerAvro.Builder clearName() {
            name = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public CustomerAvro build() {
            try {
                CustomerAvro record = new CustomerAvro();
                record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
                record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }
}










